import 'src/styles/globals.css';
import { Footer } from 'src/components/Footer';
import { Header } from 'src/components/Header';
import { ChakraProvider } from '@chakra-ui/react';
import { DataProvider } from 'src/components/Context';
import Head from 'next/head';

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>架空人物ジェネレーター</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <ChakraProvider>
        <Header />
        <DataProvider>
          <Component {...pageProps} />
        </DataProvider>
        <Footer />
      </ChakraProvider>
    </>
  );
}
